---

plugins:
  - jest
  - babel

parser: babel-eslint

env:
  node: true
  jest: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  class-methods-use-this: off
  no-param-reassign: ['error', { 'props': false }]

